#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_RR_MODE|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_HIERARICHAL_VIEW|$K_ND_SVR

NETJS-003-001|10|ALL IMMEDIATELY|TIME 00:01:00|ALL IMMEDIATELY|nsecomnodejs|127.0.0.1 10.10.30.28:3000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|1 10.10.30.48:7892 NETJS-003-001
NETJS-003-002|10|ALL IMMEDIATELY|TIME 00:01:00|ALL IMMEDIATELY|nsecomnodejs|127.0.0.1 10.10.30.28:3000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|1 10.10.30.48:7892 NETJS-003-002
NETJS-003-003|10|ALL IMMEDIATELY|TIME 00:01:00|ALL IMMEDIATELY|nsecomnodejs|127.0.0.1 10.10.30.28:3000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|1 10.10.30.48:7892 NETJS-003-003

